[build]
default-target = "x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "CARGO_TERM_COLOR",
    "GITHUB_ACTIONS", 
    "GITHUB_REF",
    "GITHUB_SHA",
    "RUST_BACKTRACE",
    "RUSTFLAGS"
]